-- ==============================================================
-- GENERA SPs y SUS TRANSACCIONES NECESARIAS PARA EL ABM
-- ==============================================================

-- ==============================================================
-- CONFIGURACION
-- ==============================================================
DECLARE @CALL_TYPE_CODE VARCHAR(20), @ABM_NAME VARCHAR(50), @ABM_CODE VARCHAR(20)

SET @CALL_TYPE_CODE = 'CODIGO_DE_ACTIVIDAD' 
SET @ABM_NAME = 'ABM Name'
SET @ABM_CODE = 'ABM_CODE'

-- ==============================================================
-- GENERACION
-- ==============================================================
DECLARE @PKEY_SP			VARCHAR(20),
		@JOB_TYPE_CODE		VARCHAR(20),
		@PKEY_CALL_TYPE		VARCHAR(20),
		@PKEY_SP_PRM		VARCHAR(20), 
		@PKEY_TRANSACTIONS	VARCHAR(20),
		@SP_CODE			VARCHAR(20),
		@SP_DESCRIPCION		VARCHAR(100)

-- Obtengo PKEY de la Actividad
SELECT @PKEY_CALL_TYPE = PKEY FROM CALL_TYPE WHERE CALL_TYPE_CODE = @CALL_TYPE_CODE 
-- Obtengo codigo del proceso
SELECT @JOB_TYPE_CODE = JOB_TYPE_CODE FROM JOB_TYPE where PKEY  = (SELECT PAR_KEY FROM CALL_TYPE WHERE PKEY = @PKEY_CALL_TYPE)


-- ==============================================================
-- SP GRILLA DEL ABM
-- ==============================================================
SET @SP_CODE = @JOB_TYPE_CODE + '_GR_' + @ABM_CODE
SET @SP_DESCRIPCION = @JOB_TYPE_CODE + ' - Grilla ' + @ABM_NAME

-- Nuevo SP
EXEC PA_SYS_OBTIENE_PKEY 'STORED_PROCEDURES',@PKEY_SP OUT
INSERT INTO STORED_PROCEDURES (PKEY, TS_BEGIN, TS_END, TS_USER_ID, RETURN_CODE_IDR,SP_CODE,PAR_KEY,SP_NAME,SP_TYPE_CODE,SP_TIME_OUT,SP_TYPE_IDR,SP_DSN, SP_UID,SP_PWD,LOCAL_IDR,SP_OBLIG,SP_CHECK,SP_DISPONIBLE,ENTIDAD_IDR, SP_DESCRIPCION)
VALUES ( @PKEY_SP, GetDate() , GetDate() ,'ADMINISTRADOR','0',@SP_CODE,@PKEY_CALL_TYPE,@SP_CODE,@CALL_TYPE_CODE,5,'Atencion',' ',' ',' ','1','N',0,'0','0', @SP_DESCRIPCION)

-- Parámetros de Entrada del SP Nuevo
EXEC PA_SYS_OBTIENE_PKEY 'SP_PRM_IN',@PKEY_SP_PRM OUT
INSERT INTO SP_PRM_IN (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, SP_CODE, PRM_TYPE, PRM_SUBTYPE, PRM_VAL, PRM_CODE,PRM_DESDE,PRM_HASTA,PRM_INDEX,PRM_DATA_TYPE,PRM_LENGTH,PRM_NAME) 
VALUES ( @PKEY_SP_PRM, GetDate() , GetDate() ,@PKEY_SP,'ADMINISTRACION',@SP_CODE,'Variable','Atributo fijo (Proceso)','ATT.JOB_PKEY','P_PKEY_JOB',1,100,1,'200',100,'P_PKEY_JOB')

-- ==============================================================
-- SP ALTA
-- ==============================================================
SET @SP_CODE = @JOB_TYPE_CODE + '_ADD_' + @ABM_CODE
SET @SP_DESCRIPCION = @JOB_TYPE_CODE + ' - Alta ' + @ABM_NAME

-- Nuevo SP
EXEC PA_SYS_OBTIENE_PKEY 'STORED_PROCEDURES',@PKEY_SP OUT
INSERT INTO STORED_PROCEDURES (PKEY, TS_BEGIN, TS_END, TS_USER_ID, RETURN_CODE_IDR,SP_CODE,PAR_KEY,SP_NAME,SP_TYPE_CODE,SP_TIME_OUT,SP_TYPE_IDR,SP_DSN, SP_UID,SP_PWD,LOCAL_IDR,SP_OBLIG,SP_CHECK,SP_DISPONIBLE,ENTIDAD_IDR, SP_DESCRIPCION)
VALUES ( @PKEY_SP, GetDate() , GetDate() ,'ADMINISTRADOR','0',@SP_CODE,@PKEY_CALL_TYPE,@SP_CODE,@CALL_TYPE_CODE,5,'Atencion',' ',' ',' ','1','N',0,'0','0', @SP_DESCRIPCION)

-- Parámetros de Entrada del SP Nuevo
EXEC PA_SYS_OBTIENE_PKEY 'SP_PRM_IN',@PKEY_SP_PRM OUT
INSERT INTO SP_PRM_IN (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, SP_CODE, PRM_TYPE, PRM_SUBTYPE, PRM_VAL, PRM_CODE,PRM_DESDE,PRM_HASTA,PRM_INDEX,PRM_DATA_TYPE,PRM_LENGTH,PRM_NAME) 
VALUES ( @PKEY_SP_PRM, GetDate() , GetDate() ,@PKEY_SP,'ADMINISTRACION',@SP_CODE,'Variable','Atributo fijo (Proceso)','ATT.JOB_PKEY','P_PKEY_JOB',1,100,1,'200',100,'P_PKEY_JOB')

-- Parámetros de Salida del SP Nuevo
EXEC PA_SYS_OBTIENE_PKEY 'SP_PRM_OUT',@PKEY_SP_PRM OUT
INSERT INTO  SP_PRM_OUT (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, SP_CODE, PRM_NAME,  PRM_CODE,PRM_LENGTH,PRM_INDEX,PRM_DATA_TYPE) 
VALUES ( @PKEY_SP_PRM, GetDate() , GetDate() ,@PKEY_SP,'ADMINISTRADOR',@SP_CODE,'P_OUT_CODE','P_OUT_CODE',30,1,'200')

EXEC PA_SYS_OBTIENE_PKEY 'SP_PRM_OUT',@PKEY_SP_PRM OUT
INSERT INTO  SP_PRM_OUT (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, SP_CODE, PRM_NAME,  PRM_CODE,PRM_LENGTH,PRM_INDEX,PRM_DATA_TYPE) 
VALUES ( @PKEY_SP_PRM, GetDate() , GetDate() ,@PKEY_SP,'ADMINISTRADOR',@SP_CODE,'P_OUT_MSG','P_OUT_MSG',2000,2,'200')

-- Transacción
EXEC PA_SYS_OBTIENE_PKEY 'TRANSACTIONS',@PKEY_TRANSACTIONS OUT
INSERT INTO TRANSACTIONS (PKEY, TS_BEGIN, TS_END, TS_USER_ID, RETURN_CODE_IDR,TRAN_CODE,PAR_KEY,DESCRIPTION,TRAN_TYPE,CALL_TYPE_CODE,TRAN_PROGRAM,TRAN_PORT_NUMBER,TRAN_HOST_NAME,TRANS_TIME_OUT,TRAN_IDR,HOST_TYPE,TRIM_PARAMETERS) 
VALUES ( @PKEY_TRANSACTIONS, GetDate() , GetDate() ,'ADMINISTRADOR','0',@SP_CODE,@PKEY_CALL_TYPE,@SP_DESCRIPCION,'Stored Procedure',@CALL_TYPE_CODE,@SP_CODE,' ',' ',5,'Atencion',' ','1')


-- ==============================================================
-- SP MODIFICACION
-- ==============================================================
SET @SP_CODE = @JOB_TYPE_CODE + '_MOD_' + @ABM_CODE
SET @SP_DESCRIPCION = @JOB_TYPE_CODE + ' - Mod ' + @ABM_NAME

-- Nuevo SP
EXEC PA_SYS_OBTIENE_PKEY 'STORED_PROCEDURES',@PKEY_SP OUT
INSERT INTO STORED_PROCEDURES (PKEY, TS_BEGIN, TS_END, TS_USER_ID, RETURN_CODE_IDR,SP_CODE,PAR_KEY,SP_NAME,SP_TYPE_CODE,SP_TIME_OUT,SP_TYPE_IDR,SP_DSN, SP_UID,SP_PWD,LOCAL_IDR,SP_OBLIG,SP_CHECK,SP_DISPONIBLE,ENTIDAD_IDR, SP_DESCRIPCION)
VALUES ( @PKEY_SP, GetDate() , GetDate() ,'ADMINISTRADOR','0',@SP_CODE,@PKEY_CALL_TYPE,@SP_CODE,@CALL_TYPE_CODE,5,'Atencion',' ',' ',' ','1','N',0,'0','0', @SP_DESCRIPCION)

-- Parámetros de Entrada del SP Nuevo
EXEC PA_SYS_OBTIENE_PKEY 'SP_PRM_IN',@PKEY_SP_PRM OUT
INSERT INTO SP_PRM_IN (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, SP_CODE, PRM_TYPE, PRM_SUBTYPE, PRM_VAL, PRM_CODE,PRM_DESDE,PRM_HASTA,PRM_INDEX,PRM_DATA_TYPE,PRM_LENGTH,PRM_NAME) 
VALUES ( @PKEY_SP_PRM, GetDate() , GetDate() ,@PKEY_SP,'ADMINISTRACION',@SP_CODE,'Variable','Atributo fijo (Proceso)','ATT.JOB_PKEY','P_PKEY_JOB',1,100,1,'200',100,'P_PKEY_JOB')

-- Parámetros de Salida del SP Nuevo
EXEC PA_SYS_OBTIENE_PKEY 'SP_PRM_OUT',@PKEY_SP_PRM OUT
INSERT INTO  SP_PRM_OUT (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, SP_CODE, PRM_NAME,  PRM_CODE,PRM_LENGTH,PRM_INDEX,PRM_DATA_TYPE) 
VALUES ( @PKEY_SP_PRM, GetDate() , GetDate() ,@PKEY_SP,'ADMINISTRADOR',@SP_CODE,'P_OUT_CODE','P_OUT_CODE',30,1,'200')

EXEC PA_SYS_OBTIENE_PKEY 'SP_PRM_OUT',@PKEY_SP_PRM OUT
INSERT INTO  SP_PRM_OUT (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, SP_CODE, PRM_NAME,  PRM_CODE,PRM_LENGTH,PRM_INDEX,PRM_DATA_TYPE) 
VALUES ( @PKEY_SP_PRM, GetDate() , GetDate() ,@PKEY_SP,'ADMINISTRADOR',@SP_CODE,'P_OUT_MSG','P_OUT_MSG',2000,2,'200')

-- Transacción
EXEC PA_SYS_OBTIENE_PKEY 'TRANSACTIONS',@PKEY_TRANSACTIONS OUT
INSERT INTO TRANSACTIONS (PKEY, TS_BEGIN, TS_END, TS_USER_ID, RETURN_CODE_IDR,TRAN_CODE,PAR_KEY,DESCRIPTION,TRAN_TYPE,CALL_TYPE_CODE,TRAN_PROGRAM,TRAN_PORT_NUMBER,TRAN_HOST_NAME,TRANS_TIME_OUT,TRAN_IDR,HOST_TYPE,TRIM_PARAMETERS) 
VALUES ( @PKEY_TRANSACTIONS, GetDate() , GetDate() ,'ADMINISTRADOR','0',@SP_CODE,@PKEY_CALL_TYPE,@SP_DESCRIPCION,'Stored Procedure',@CALL_TYPE_CODE,@SP_CODE,' ',' ',5,'Atencion',' ','1')


-- ==============================================================
-- SP BAJA
-- ==============================================================
SET @SP_CODE = @JOB_TYPE_CODE + '_DEL_' + @ABM_CODE
SET @SP_DESCRIPCION = @JOB_TYPE_CODE + ' - Baja ' + @ABM_NAME

-- Nuevo SP
EXEC PA_SYS_OBTIENE_PKEY 'STORED_PROCEDURES',@PKEY_SP OUT
INSERT INTO STORED_PROCEDURES (PKEY, TS_BEGIN, TS_END, TS_USER_ID, RETURN_CODE_IDR,SP_CODE,PAR_KEY,SP_NAME,SP_TYPE_CODE,SP_TIME_OUT,SP_TYPE_IDR,SP_DSN, SP_UID,SP_PWD,LOCAL_IDR,SP_OBLIG,SP_CHECK,SP_DISPONIBLE,ENTIDAD_IDR, SP_DESCRIPCION)
VALUES ( @PKEY_SP, GetDate() , GetDate() ,'ADMINISTRADOR','0',@SP_CODE,@PKEY_CALL_TYPE,@SP_CODE,@CALL_TYPE_CODE,5,'Atencion',' ',' ',' ','1','N',0,'0','0', @SP_DESCRIPCION)

-- Parámetros de Entrada del SP Nuevo
EXEC PA_SYS_OBTIENE_PKEY 'SP_PRM_IN',@PKEY_SP_PRM OUT
INSERT INTO SP_PRM_IN (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, SP_CODE, PRM_TYPE, PRM_SUBTYPE, PRM_VAL, PRM_CODE,PRM_DESDE,PRM_HASTA,PRM_INDEX,PRM_DATA_TYPE,PRM_LENGTH,PRM_NAME) 
VALUES ( @PKEY_SP_PRM, GetDate() , GetDate() ,@PKEY_SP,'ADMINISTRACION',@SP_CODE,'Variable','Atributo fijo (Proceso)','ATT.JOB_PKEY','P_PKEY_JOB',1,100,1,'200',100,'P_PKEY_JOB')

-- Transacción
EXEC PA_SYS_OBTIENE_PKEY 'TRANSACTIONS',@PKEY_TRANSACTIONS OUT
INSERT INTO TRANSACTIONS (PKEY, TS_BEGIN, TS_END, TS_USER_ID, RETURN_CODE_IDR,TRAN_CODE,PAR_KEY,DESCRIPTION,TRAN_TYPE,CALL_TYPE_CODE,TRAN_PROGRAM,TRAN_PORT_NUMBER,TRAN_HOST_NAME,TRANS_TIME_OUT,TRAN_IDR,HOST_TYPE,TRIM_PARAMETERS) 
VALUES ( @PKEY_TRANSACTIONS, GetDate() , GetDate() ,'ADMINISTRADOR','0',@SP_CODE,@PKEY_CALL_TYPE,@SP_DESCRIPCION,'Stored Procedure',@CALL_TYPE_CODE,@SP_CODE,' ',' ',5,'Atencion',' ','1')

-- ==============================================================
-- SP LIMPIA
-- ==============================================================
SET @SP_CODE = @JOB_TYPE_CODE + '_CLR_' + @ABM_CODE
SET @SP_DESCRIPCION = @JOB_TYPE_CODE + ' - Limpia ' + @ABM_NAME

-- Nuevo SP
EXEC PA_SYS_OBTIENE_PKEY 'STORED_PROCEDURES',@PKEY_SP OUT
INSERT INTO STORED_PROCEDURES (PKEY, TS_BEGIN, TS_END, TS_USER_ID, RETURN_CODE_IDR,SP_CODE,PAR_KEY,SP_NAME,SP_TYPE_CODE,SP_TIME_OUT,SP_TYPE_IDR,SP_DSN, SP_UID,SP_PWD,LOCAL_IDR,SP_OBLIG,SP_CHECK,SP_DISPONIBLE,ENTIDAD_IDR, SP_DESCRIPCION)
VALUES ( @PKEY_SP, GetDate() , GetDate() ,'ADMINISTRADOR','0',@SP_CODE,@PKEY_CALL_TYPE,@SP_CODE,@CALL_TYPE_CODE,5,'Atencion',' ',' ',' ','1','N',0,'0','0', @SP_DESCRIPCION)

-- Parámetros de Entrada del SP Nuevo
EXEC PA_SYS_OBTIENE_PKEY 'SP_PRM_IN',@PKEY_SP_PRM OUT
INSERT INTO SP_PRM_IN (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, SP_CODE, PRM_TYPE, PRM_SUBTYPE, PRM_VAL, PRM_CODE,PRM_DESDE,PRM_HASTA,PRM_INDEX,PRM_DATA_TYPE,PRM_LENGTH,PRM_NAME) 
VALUES ( @PKEY_SP_PRM, GetDate() , GetDate() ,@PKEY_SP,'ADMINISTRACION',@SP_CODE,'Variable','Atributo fijo (Proceso)','ATT.JOB_PKEY','P_PKEY_JOB',1,100,1,'200',100,'P_PKEY_JOB')

-- Transacción
EXEC PA_SYS_OBTIENE_PKEY 'TRANSACTIONS',@PKEY_TRANSACTIONS OUT
INSERT INTO TRANSACTIONS (PKEY, TS_BEGIN, TS_END, TS_USER_ID, RETURN_CODE_IDR,TRAN_CODE,PAR_KEY,DESCRIPTION,TRAN_TYPE,CALL_TYPE_CODE,TRAN_PROGRAM,TRAN_PORT_NUMBER,TRAN_HOST_NAME,TRANS_TIME_OUT,TRAN_IDR,HOST_TYPE,TRIM_PARAMETERS) 
VALUES ( @PKEY_TRANSACTIONS, GetDate() , GetDate() ,'ADMINISTRADOR','0',@SP_CODE,@PKEY_CALL_TYPE,@SP_DESCRIPCION,'Stored Procedure',@CALL_TYPE_CODE,@SP_CODE,' ',' ',5,'Atencion',' ','1')
