-- ==============================================================
-- GENERA FLUJO CON TRANSACCIONES, PANTALLAS y SALTOS
-- ==============================================================

ALTER PROCEDURE WIKI_GENERA_FLUJOS_ESTRUCTURA
	(
		@PKEY_ESTRUCTURA			VARCHAR(20),
		@PKEY_ESTRUCTURA_SALTO		VARCHAR(20),
		@DESC_ESTRUCTURA_SALTO		VARCHAR(120),
		@SP_CODE_PRE				VARCHAR(20),
		@SP_DESCRIPCION_PRE			VARCHAR(100),
		@SP_CODE					VARCHAR(20),
		@SP_DESCRIPCION				VARCHAR(100)
	)
AS BEGIN

-- ==============================================================
-- CONFIGURACION
-- ==============================================================
DECLARE 
	@PKEY_PANTALLA	VARCHAR(20),
	@PKEY_TR		VARCHAR(20),
	@PKEY_FLECHA	VARCHAR(20)


-- ==============================================================
-- ESTRUCTURAS DE ALTA Y MODIFICACION
-- ==============================================================

-- Pantalla Roja
EXEC PA_SYS_OBTIENE_PKEY 'CONV_STRUCTURE_STEP_NORMAL',@PKEY_PANTALLA OUT
INSERT INTO CONV_STRUCTURE_STEP_NORMAL (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, STEP_NUMBER, STEP_TYPE_CODE, STEP_AGENT_CAPTION, BACK_COLOR,  CTOP, CLEFT, CWIDTH, CHEIGHT ,FIRST_IDR) 
VALUES ( @PKEY_PANTALLA, GetDate() , GetDate() ,@PKEY_ESTRUCTURA,'ADMINISTRADOR',1,'script',@SP_DESCRIPCION,'16777215',217,505,100,70,'0')

-- FLECHA CONTINUAR
EXEC PA_SYS_OBTIENE_PKEY 'STEP_NORMAL_FLOW',@PKEY_FLECHA OUT
INSERT INTO STEP_NORMAL_FLOW (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID,   STEP_NUMBER, STEP_TO_NUMBER,CONV_STRUCTURE_KEY,FLOW_TYPE_CODE,STEP_TO_CAPTION) 
VALUES ( @PKEY_FLECHA, GetDate() , GetDate() ,@PKEY_PANTALLA,'ADMINISTRADOR',1,6,@PKEY_ESTRUCTURA,'flujonormal',' ')




-- Transacción PRE PANTALLA
EXEC PA_SYS_OBTIENE_PKEY 'CONV_STRUCTURE_STEP_TRAN',@PKEY_TR OUT
INSERT INTO CONV_STRUCTURE_STEP_TRAN (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, STEP_NUMBER, STEP_TYPE_CODE, STEP_AGENT_CAPTION, BACK_COLOR,  CTOP, CLEFT, CWIDTH, CHEIGHT ,FIRST_IDR,TRAN_CODE) 
VALUES ( @PKEY_TR, GetDate() , GetDate() ,@PKEY_ESTRUCTURA,'ADMINISTRADOR',2,'transaccion',@SP_DESCRIPCION_PRE,'0',217,247,100,70,'1',@SP_CODE_PRE)

-- FLECHA OK
EXEC PA_SYS_OBTIENE_PKEY 'STEP_TRANSACTION_FLOW',@PKEY_FLECHA OUT
INSERT INTO STEP_TRANSACTION_FLOW (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID,  STEP_NUMBER,STEP_TO_NUMBER,CONV_STRUCTURE_KEY,FLOW_TYPE_CODE,RETURN_CODE,TRAN_CODE,PRM_VALUE,FORMULA_DETAIL,PRM_IDR,STEP_TO_CAPTION,EXCEPTION_MESSAGE) 
VALUES ( @PKEY_FLECHA, GetDate() , GetDate() ,@PKEY_TR,'ADMINISTRADOR',2,1,@PKEY_ESTRUCTURA,'flujotran','OK',@SP_CODE_PRE,'OK',' ',' ','OK',' ')

-- FLECHA TIMEOUT
EXEC PA_SYS_OBTIENE_PKEY 'STEP_TRANSACTION_FLOW',@PKEY_FLECHA OUT
INSERT INTO STEP_TRANSACTION_FLOW (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID,  STEP_NUMBER,STEP_TO_NUMBER,CONV_STRUCTURE_KEY,FLOW_TYPE_CODE,RETURN_CODE,TRAN_CODE,PRM_VALUE,FORMULA_DETAIL,PRM_IDR,STEP_TO_CAPTION,EXCEPTION_MESSAGE) 
VALUES ( @PKEY_FLECHA, GetDate() , GetDate() ,@PKEY_TR,'ADMINISTRADOR',2,1,@PKEY_ESTRUCTURA,'flujotran','TIMEOUT',@SP_CODE_PRE,'TIMEOUT',' ',' ','TimeOut','TimeOut')

-- FLECHA ERROR
EXEC PA_SYS_OBTIENE_PKEY 'STEP_TRANSACTION_FLOW',@PKEY_FLECHA OUT
INSERT INTO STEP_TRANSACTION_FLOW (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID,  STEP_NUMBER,STEP_TO_NUMBER,CONV_STRUCTURE_KEY,FLOW_TYPE_CODE,RETURN_CODE,TRAN_CODE,PRM_VALUE,FORMULA_DETAIL,PRM_IDR,STEP_TO_CAPTION,EXCEPTION_MESSAGE) 
VALUES ( @PKEY_FLECHA, GetDate() , GetDate() ,@PKEY_TR,'ADMINISTRADOR',2,1,@PKEY_ESTRUCTURA,'flujotran','ERROR',@SP_CODE_PRE,'ERROR',' ',' ','Error','Error')




-- Transacción POST PANTALLA
EXEC PA_SYS_OBTIENE_PKEY 'CONV_STRUCTURE_STEP_TRAN',@PKEY_TR OUT
INSERT INTO CONV_STRUCTURE_STEP_TRAN (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, STEP_NUMBER, STEP_TYPE_CODE, STEP_AGENT_CAPTION, BACK_COLOR,  CTOP, CLEFT, CWIDTH, CHEIGHT ,FIRST_IDR,TRAN_CODE) 
VALUES ( @PKEY_TR, GetDate() , GetDate() ,@PKEY_ESTRUCTURA,'ADMINISTRADOR',6,'transaccion',@SP_DESCRIPCION,'0',393,505,100,70,'0',@SP_CODE)

-- Salto
EXEC PA_SYS_OBTIENE_PKEY 'CONV_STRUCTURE_STEP_NORMAL',@PKEY_FLECHA OUT
INSERT INTO CONV_STRUCTURE_STEP_NORMAL (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, STEP_NUMBER, STEP_TYPE_CODE, STEP_AGENT_CAPTION, BACK_COLOR,  CTOP, CLEFT, CWIDTH, CHEIGHT ,FIRST_IDR) 
VALUES ( @PKEY_FLECHA, GetDate() , GetDate() ,@PKEY_ESTRUCTURA,'ADMINISTRADOR',11,'estructura',@DESC_ESTRUCTURA_SALTO,'-2147483633',408,731,40,40,'0')

-- FLECHA OKEY
EXEC PA_SYS_OBTIENE_PKEY 'STEP_TRANSACTION_FLOW',@PKEY_FLECHA OUT
INSERT INTO STEP_TRANSACTION_FLOW (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID,  STEP_NUMBER,CONV_STRUCTURE_TO_KEY,STEP_TO_NUMBER,CONV_STRUCTURE_KEY,FLOW_TYPE_CODE,RETURN_CODE,TRAN_CODE,PRM_VALUE,FORMULA_DETAIL,PRM_IDR,STEP_TO_CAPTION,EXCEPTION_MESSAGE) 
VALUES ( @PKEY_FLECHA, GetDate() , GetDate() ,@PKEY_TR,'ADMINISTRADOR',6,@PKEY_ESTRUCTURA_SALTO,11,@PKEY_ESTRUCTURA,'flujostrtran',' ',@SP_CODE,'%G'+@SP_CODE+'.P_OUT_CODE%P=%V0','Transacción (Actividad) - '+@SP_DESCRIPCION+'.P_OUT_CODE;=;0;','formula','OKEY',' ')

-- FLECHA VALIDACION
EXEC PA_SYS_OBTIENE_PKEY 'STEP_TRANSACTION_FLOW',@PKEY_FLECHA OUT
INSERT INTO STEP_TRANSACTION_FLOW (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID,  STEP_NUMBER,STEP_TO_NUMBER,CONV_STRUCTURE_KEY,FLOW_TYPE_CODE,RETURN_CODE,TRAN_CODE,PRM_VALUE,FORMULA_DETAIL,PRM_IDR,STEP_TO_CAPTION,EXCEPTION_MESSAGE) 
VALUES ( @PKEY_FLECHA, GetDate() , GetDate() ,@PKEY_TR,'ADMINISTRADOR',6,2,@PKEY_ESTRUCTURA,'flujotran',' ',@SP_CODE,'%G'+@SP_CODE+'.P_OUT_CODE%P=%V1','Transacción (Actividad) - '+@SP_DESCRIPCION+'.P_OUT_CODE;=;1;','formula','VALIDACION',' ')

END