-- ==============================================================
-- GENERA 5 ESTRUCTURAS BASE PARA EL ABM
-- (PANTALLA ABM, ALTA, MODIFICACION, BAJA, LIMPIA)
-- ==============================================================

-- ==============================================================
-- CONFIGURACION
-- ==============================================================
DECLARE @CALL_TYPE_CODE VARCHAR(20), @ABM_NAME VARCHAR(50)

SET @CALL_TYPE_CODE = 'CODIGO_DE_ACTIVIDAD' 
SET @ABM_NAME = 'NOMBRE DEL ABM'

-- ==============================================================
-- GENERACION
-- ==============================================================
DECLARE @PKEY VARCHAR(20), @CONV_STRUCTURE_SEQ NUMERIC(15,0),@PKEY_CALL_TYPE VARCHAR(20)

-- Obtengo PKEY de la Actividad
SELECT @PKEY_CALL_TYPE = PKEY FROM CALL_TYPE WHERE CALL_TYPE_CODE = @CALL_TYPE_CODE 

-- Obtengo secuencia de la nueva estructura y le genero una pkey
SELECT @CONV_STRUCTURE_SEQ = MAX(CONV_STRUCTURE_SEQ)+1 FROM CALL_CONV_STRUCTURES WHERE PAR_KEY= @PKEY_CALL_TYPE
EXEC PA_SYS_OBTIENE_PKEY 'CALL_CONV_STRUCTURES',@PKEY OUT

-- Creo una nueva estructura
INSERT INTO CALL_CONV_STRUCTURES (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, CALL_TYPE_CODE,CONV_STRUCTURE_DESC,CONV_STRUCTURE_SEQ,STOP,SLEFT,SWIDTH,SHEIGHT,BACKGROUND_FILE_WIN,BACKGROUND_FILE_WEB,CONV_STRUCTURE_DETAILS) 
VALUES (@PKEY, GetDate() , GetDate() ,@PKEY_CALL_TYPE,'ADMINISTRADOR',@CALL_TYPE_CODE,CONVERT(VARCHAR,@CONV_STRUCTURE_SEQ)+' - Pantalla '+@ABM_NAME ,@CONV_STRUCTURE_SEQ,0,0,0,0,'','','')

-- Repito para las otra 4 ESTRUCTURAS
SELECT @CONV_STRUCTURE_SEQ = MAX(CONV_STRUCTURE_SEQ)+1 FROM CALL_CONV_STRUCTURES WHERE PAR_KEY= @PKEY_CALL_TYPE
EXEC PA_SYS_OBTIENE_PKEY 'CALL_CONV_STRUCTURES',@PKEY OUT

INSERT INTO CALL_CONV_STRUCTURES (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, CALL_TYPE_CODE,CONV_STRUCTURE_DESC,CONV_STRUCTURE_SEQ,STOP,SLEFT,SWIDTH,SHEIGHT,BACKGROUND_FILE_WIN,BACKGROUND_FILE_WEB,CONV_STRUCTURE_DETAILS) 
VALUES (@PKEY, GetDate() , GetDate() ,@PKEY_CALL_TYPE,'ADMINISTRADOR',@CALL_TYPE_CODE,CONVERT(VARCHAR,@CONV_STRUCTURE_SEQ)+' - Alta '+@ABM_NAME ,@CONV_STRUCTURE_SEQ,0,0,0,0,'','','')

SELECT @CONV_STRUCTURE_SEQ = MAX(CONV_STRUCTURE_SEQ)+1 FROM CALL_CONV_STRUCTURES WHERE PAR_KEY= @PKEY_CALL_TYPE
EXEC PA_SYS_OBTIENE_PKEY 'CALL_CONV_STRUCTURES',@PKEY OUT

INSERT INTO CALL_CONV_STRUCTURES (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, CALL_TYPE_CODE,CONV_STRUCTURE_DESC,CONV_STRUCTURE_SEQ,STOP,SLEFT,SWIDTH,SHEIGHT,BACKGROUND_FILE_WIN,BACKGROUND_FILE_WEB,CONV_STRUCTURE_DETAILS) 
VALUES (@PKEY, GetDate() , GetDate() ,@PKEY_CALL_TYPE,'ADMINISTRADOR',@CALL_TYPE_CODE,CONVERT(VARCHAR,@CONV_STRUCTURE_SEQ)+' - Mod '+@ABM_NAME ,@CONV_STRUCTURE_SEQ,0,0,0,0,'','','')

SELECT @CONV_STRUCTURE_SEQ = MAX(CONV_STRUCTURE_SEQ)+1 FROM CALL_CONV_STRUCTURES WHERE PAR_KEY= @PKEY_CALL_TYPE
EXEC PA_SYS_OBTIENE_PKEY 'CALL_CONV_STRUCTURES',@PKEY OUT

INSERT INTO CALL_CONV_STRUCTURES (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, CALL_TYPE_CODE,CONV_STRUCTURE_DESC,CONV_STRUCTURE_SEQ,STOP,SLEFT,SWIDTH,SHEIGHT,BACKGROUND_FILE_WIN,BACKGROUND_FILE_WEB,CONV_STRUCTURE_DETAILS) 
VALUES (@PKEY, GetDate() , GetDate() ,@PKEY_CALL_TYPE,'ADMINISTRADOR',@CALL_TYPE_CODE,CONVERT(VARCHAR,@CONV_STRUCTURE_SEQ)+' - Baja '+@ABM_NAME ,@CONV_STRUCTURE_SEQ,0,0,0,0,'','','')

SELECT @CONV_STRUCTURE_SEQ = MAX(CONV_STRUCTURE_SEQ)+1 FROM CALL_CONV_STRUCTURES WHERE PAR_KEY= @PKEY_CALL_TYPE
EXEC PA_SYS_OBTIENE_PKEY 'CALL_CONV_STRUCTURES',@PKEY OUT

INSERT INTO CALL_CONV_STRUCTURES (PKEY, TS_BEGIN, TS_END, PAR_KEY, TS_USER_ID, CALL_TYPE_CODE,CONV_STRUCTURE_DESC,CONV_STRUCTURE_SEQ,STOP,SLEFT,SWIDTH,SHEIGHT,BACKGROUND_FILE_WIN,BACKGROUND_FILE_WEB,CONV_STRUCTURE_DETAILS) 
VALUES (@PKEY, GetDate() , GetDate() ,@PKEY_CALL_TYPE,'ADMINISTRADOR',@CALL_TYPE_CODE,CONVERT(VARCHAR,@CONV_STRUCTURE_SEQ)+' - Limpia '+@ABM_NAME ,@CONV_STRUCTURE_SEQ,0,0,0,0,'','','')
