-- VERSION 2.0
-- CONSULTA DE LOG DE TRANSACCIONES DE UN PROCESO EN PARTICULAR
-- ANALIZAR LOS REGISROS CUYA COLUMNA "RESULTADO" <> 'OK' Y VER LOS PARAMETROS DE ENTRADA Y SALIDA

DECLARE
@UNIDAD AS VARCHAR(100),
@PKEY_JOB AS VARCHAR (100),
@NRO_PROCESO AS NUMERIC(10)

----------------------------------------------------------------------------------------------------------
SET @NRO_PROCESO = 127882 -- DEFINIR AQUI EL NRO. DE PROCESO DEL CUAL SE CONSULTARÁ EL LOG DE TRANSACCIONES
----------------------------------------------------------------------------------------------------------

SELECT @PKEY_JOB = PKEY_PHYSICAL_JOB FROM DSS_TBPHYSICAL_JOB
WHERE JOB_SEQ = @NRO_PROCESO

SELECT
	JT.JOB_TYPE_CODE + '|' + JT.JOB_TYPE_DESC AS 'PROCESO'
	,CT.CALL_TYPE_CODE + '|' + CT.CALL_TYPE_DESC AS 'ACTIVIDAD'
	,PC.CALL_DATE_TIME AS 'FECHA RETOMA'
	,PC.CALL_DATE AS 'FECHA RETOMA2'
	,AC.ATT_RESULT_CODE AS 'RESULTADO ACTIVIDAD'
	,CCS.CONV_STRUCTURE_DESC AS 'ESTRUCTURA'
	,CASE
		WHEN CCS.PKEY = CSST.PAR_KEY THEN CSST.TRAN_CODE
		WHEN CCS.PKEY = CSSN.PAR_KEY THEN CSSN.STEP_AGENT_CAPTION
	END AS 'OBJETO'
	,PCT.TRANS_TYPE AS 'TIPO'
	,PCT.TRANS_CODE						AS 'Transacción'
	,PCT.TRANS_RESULT_CODE				AS 'Resultado'
	,PCT.TS_BEGIN						AS 'Fecha'
	,DATEDIFF (SS, PCT.TS_BEGIN, PCT.TS_END) AS 'Tiempo'
	,TRANS_PRM_IN					AS 'Parametro Entrada'
	,(REPLACE(REPLACE(PCT.TRANS_PRM_IN , '<', '&lt;'),'>','&gt;')) AS 'Parametro Entrada'
	,REPLACE(REPLACE(PCT.TRANS_PRM_OUT, '<', '&lt;'),'>','&gt;')AS 'Parametro Salida'
	,PCT.TS_USER_ID AS 'USUARIO'
FROM PHYSICAL_CALL_TRANSACTIONS PCT
LEFT JOIN DSS_TBPHYSICAL_CALL_CONV_STEPS PCCS ON  PCCS.ID_CONV_STEPS = PCT.PAR_KEY -- PASO DE LA RETOMA
LEFT JOIN CONV_STRUCTURE_STEP_NORMAL CSSN ON PCCS.PKEY_CONV_STEP = CSSN.PKEY -- PANTALLA
LEFT JOIN CONV_STRUCTURE_STEP_TRAN CSST ON PCCS.PKEY_CONV_STEP = CSST.PKEY -- TRANSACCION
LEFT JOIN CALL_CONV_STRUCTURES CCS ON (CCS.PKEY = CSSN.PAR_KEY OR CCS.PKEY = CSST.PAR_KEY) -- ESTRUCTURA
LEFT JOIN CALL_TYPE CT ON CT.PKEY = CCS.PAR_KEY -- ACTIVIDAD
LEFT JOIN JOB_TYPE JT ON JT.PKEY = CT.PAR_KEY -- PROCESO
LEFT JOIN DSS_TBPHYSICAL_CALL PC ON PCCS.PKEY_PHYSICAL_CALL = PC.PKEY_PHYSICAL_CALL -- INSTANCIA DE RETOMA
LEFT JOIN DSS_TBATTENDED_CUSTOMER AC ON PC.PKEY_ATTENDED_CUSTOMER = AC.PKEY_ATTENDED_CUSTOMER -- INSTANCIA DE ACTIVIDAD

WHERE 1=1
AND AC.PKEY_PHYSICAL_JOB = @PKEY_JOB -- PROCESO ESPECIFICO			
ORDER BY PCT.TS_BEGIN DESC









