
-- DEVUELVE LOS BOTONES;COMBOS;ETC DE UNA PANTALLA
-- EL CAMPO VAL_TBL_NAME DEVUELVE LA PKEY DE LA CAT_DATA ASOCIADA A ESE COMBO BOX

SELECT T1.* from DETAIL_FIELD T1
INNER JOIN CONV_STRUCTURE_STEP_NORMAL T2 ON T1.PAR_KEY = T2.PKEY
WHERE T2.PKEY = '0000000028_55' -- CODIGO QUE DA EL DESIGNER AL HACER CLIC SECUNDARIO EN EL FORMULARIO Y 'COPIAR A'