-- CONSULTA DE LOG DE TRANSACCIONES DEL PROCESO PERFIL_CLIENTE / ABM_GENERAL

DECLARE
@UNIDAD1 AS VARCHAR(100),
@PKEY_JOB1 AS VARCHAR (100),
@NRO_PROCESO1 AS NUMERIC(10),
@UNIDAD2 AS VARCHAR(100),
@PKEY_JOB2 AS VARCHAR (100),
@NRO_PROCESO2 AS NUMERIC(10),
@USUARIO AS VARCHAR(100)

----------------------------------------------------------------------
SET @USUARIO='ech'  -- INGRESE ENTRE LAS COMILLAS SU USUARIO DE ENGAGE
----------------------------------------------------------------------

SELECT TOP 1 @NRO_PROCESO1=JOB_SEQ
FROM PHYSICAL_JOB
WHERE TS_USER_ID=@USUARIO AND (JOB_TYPE_CODE='PERFIL_CLIENTE')
ORDER BY JOB_STATE_DATE DESC

SELECT TOP 1 @NRO_PROCESO2 =JOB_SEQ
FROM PHYSICAL_JOB
WHERE TS_USER_ID=@USUARIO AND (JOB_TYPE_CODE='ABM_GENERAL')
ORDER BY JOB_STATE_DATE DESC

SELECT @PKEY_JOB1 = PKEY_PHYSICAL_JOB FROM DSS_TBPHYSICAL_JOB
WHERE JOB_SEQ = @NRO_PROCESO1
SET @UNIDAD1=(SELECT ATT_GROUP_CODE FROM PHYSICAL_JOB WHERE PKEY=@PKEY_JOB1)

SELECT @PKEY_JOB2 = PKEY_PHYSICAL_JOB FROM DSS_TBPHYSICAL_JOB
WHERE JOB_SEQ = @NRO_PROCESO2
SET @UNIDAD2=(SELECT ATT_GROUP_CODE FROM PHYSICAL_JOB WHERE PKEY=@PKEY_JOB2)

SELECT
	TRANS_CODE						AS 'Transacción'
	,TRANS_RESULT_CODE				AS 'Resultado'
	,TS_BEGIN						AS 'Fecha'	
	,TS_USER_ID						AS 'Usuario'
	,DATEDIFF (MINUTE, TS_BEGIN, TS_END)AS 'Minutos'
	,DATEDIFF (SECOND, TS_BEGIN, TS_END) AS 'Segundos'
	,DATEDIFF(MILLISECOND,TS_BEGIN, TS_END) AS 'Milisegundos'
	--,TRANS_PRM_IN					AS 'Parametro Entrada'
	,(REPLACE(REPLACE(TRANS_PRM_IN , '<', '&lt;'),'>','&gt;')) AS 'Parametro Entrada'
	,REPLACE(REPLACE(TRANS_PRM_OUT, '<', '&lt;'),'>','&gt;')AS 'Parametro Salida'
FROM PHYSICAL_CALL_TRANSACTIONS

WHERE 1=1
AND PAR_KEY IN	(SELECT ID_CONV_STEPS FROM DSS_TBPHYSICAL_CALL_CONV_STEPS WHERE PKEY_PHYSICAL_CALL IN 
					(SELECT PKEY_PHYSICAL_CALL FROM DSS_TBPHYSICAL_CALL WHERE PKEY_ATTENDED_CUSTOMER IN 
						(SELECT PKEY_ATTENDED_CUSTOMER FROM DSS_TBATTENDED_CUSTOMER WHERE PKEY_PHYSICAL_JOB /*= @PKEY_JOB*/  IN
								--AND TS_BEGIN <= (SELECT MAX(TS_BEGIN) FROM DSS_TBATTENDED_CUSTOMER  WHERE PKEY_PHYSICAL_JOB = @PKEY_JOB AND ID_GROUP<>@UNIDAD)
							(SELECT PKEY_PHYSICAL_JOB FROM DSS_TBPHYSICAL_JOB WHERE JOB_SEQ = @NRO_PROCESO1
							)
						)
					)
				)	

UNION

SELECT 
	TRANS_CODE						AS 'Transacción'
	,TRANS_RESULT_CODE				AS 'Resultado'
	,TS_BEGIN						AS 'Fecha'	
	,TS_USER_ID						AS 'Usuario'
	,DATEDIFF (MINUTE, TS_BEGIN, TS_END)AS 'Minutos'
	,DATEDIFF (SECOND, TS_BEGIN, TS_END) AS 'Segundos'
	,DATEDIFF(MILLISECOND,TS_BEGIN, TS_END) AS 'Milisegundos'
	,(REPLACE(REPLACE(TRANS_PRM_IN , '<', '&lt;'),'>','&gt;')) AS 'Parametro Entrada'
	,REPLACE(REPLACE(TRANS_PRM_OUT, '<', '&lt;'),'>','&gt;')AS 'Parametro Salida'
FROM PHYSICAL_CALL_TRANSACTIONS

WHERE 1=1
AND PAR_KEY IN	(SELECT ID_CONV_STEPS FROM DSS_TBPHYSICAL_CALL_CONV_STEPS WHERE PKEY_PHYSICAL_CALL IN 
					(SELECT PKEY_PHYSICAL_CALL FROM DSS_TBPHYSICAL_CALL WHERE PKEY_ATTENDED_CUSTOMER IN 
						(SELECT PKEY_ATTENDED_CUSTOMER FROM DSS_TBATTENDED_CUSTOMER WHERE PKEY_PHYSICAL_JOB /*= @PKEY_JOB*/  IN
								--AND TS_BEGIN <= (SELECT MAX(TS_BEGIN) FROM DSS_TBATTENDED_CUSTOMER  WHERE PKEY_PHYSICAL_JOB = @PKEY_JOB AND ID_GROUP<>@UNIDAD)
							(SELECT PKEY_PHYSICAL_JOB FROM DSS_TBPHYSICAL_JOB WHERE JOB_SEQ = @NRO_PROCESO2
							)
						)
					)
				)

UNION
SELECT *
FROM (SELECT TOP 11
	TRANS_CODE						AS 'Transacción'
	,TRANS_RESULT_CODE				AS 'Resultado'
	,TS_BEGIN 						AS 'Fecha'	
	,TS_USER_ID						AS 'Usuario'
	,DATEDIFF (MINUTE, TS_BEGIN, TS_END)AS 'Minutos'
	,DATEDIFF (SECOND, TS_BEGIN, TS_END) AS 'Segundos'
	,DATEDIFF(MILLISECOND,TS_BEGIN, TS_END) AS 'Milisegundos'
	,(REPLACE(REPLACE(TRANS_PRM_IN , '<', '&lt;'),'>','&gt;')) AS 'Parametro Entrada'
	,REPLACE(REPLACE(TRANS_PRM_OUT, '<', '&lt;'),'>','&gt;')AS 'Parametro Salida'
	FROM PHYSICAL_CALL_TRANSACTIONS
	ORDER BY TS_BEGIN DESC ) AS TABLA

ORDER BY TS_BEGIN DESC