SELECT 'SIN FLECHA ERROR' AS REVISAR, C.TRAN_CODE, C.STEP_AGENT_CAPTION, CC.CALL_TYPE_CODE, CC.CONV_STRUCTURE_DESC AS ESTRUCTURA  
FROM CONV_STRUCTURE_STEP_TRAN C
LEFT JOIN CALL_CONV_STRUCTURES CC ON CC.PKEY=C.PAR_KEY 
LEFT JOIN TRANSACTIONS T ON T.TRAN_CODE=C.TRAN_CODE
WHERE C.PKEY NOT IN (SELECT PAR_KEY FROM STEP_TRANSACTION_FLOW WHERE RETURN_CODE IN ('ERROR'))
AND C.TRAN_CODE NOT IN  ('P_A_IF','P_G_IF')

UNION

SELECT 'SIN FLECHA TIMEOUT', C.TRAN_CODE, C.STEP_AGENT_CAPTION, CC.CALL_TYPE_CODE, CC.CONV_STRUCTURE_DESC AS ESTRUCTURA  
FROM CONV_STRUCTURE_STEP_TRAN C
LEFT JOIN CALL_CONV_STRUCTURES CC ON CC.PKEY=C.PAR_KEY 
LEFT JOIN TRANSACTIONS T ON T.TRAN_CODE=C.TRAN_CODE
WHERE C.PKEY NOT IN (SELECT PAR_KEY FROM STEP_TRANSACTION_FLOW WHERE RETURN_CODE IN ('TIMEOUT'))
AND C.TRAN_CODE NOT IN  ('P_A_IF','P_G_IF')

ORDER BY CALL_TYPE_CODE, ESTRUCTURA, TRAN_CODE, REVISAR